name: tips_viewer
description: a tips and trick viewer

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  flutter_riverpod: ^1.0.4
  isar: any
  isar_flutter_libs: any
  path_provider: ^2.0.11
  graphql: ^5.1.1
  url_launcher: ^6.1.5
  equatable: ^2.0.5

dev_dependencies:
  build_runner: any
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  isar_generator: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcons/playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/AppIcons/playstore.png"
    background_color: "#c7c2b3"
    theme_color: "#c7c2b3"
  windows:
    generate: true
    image_path: "assets/AppIcons/playstore.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
